kind: ConfigMap
apiVersion: v1
metadata:
  name: resources
  namespace: test-pods
data:
  boskos-resources.yaml: |
    resources:
      - type: "vpc-service"
        state: free
        names:
        - "s390x-k8s-conformance"
