apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ibmcloud-secrets-store
  namespace: test-pods
spec:
  provider:
    ibm:
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: ibmcloud-credentials
            key: api-key
---
apiVersion: v1
kind: Secret
metadata:
  name: ibmcloud-credentials
  namespace: test-pods
type: Opaque
stringData:
  api-key: "8_4f2ggYLl2C2cgJaZkfy8Nw2LgqMullnB4_3JgUh24N"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibmcloud-janitor-api-key
  namespace: test-pods
spec:
  secretStoreRef:
    name: ibmcloud-secrets-store
    kind: SecretStore
  target:
    name: ibmcloud-janitor-secret
  data:
    - secretKey: api-key
      remoteRef:
        key: https://4aa82246-ef34-421d-9a17-cd561e99e061.us-south.secrets-manager.appdomain.cloud
