apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    ibm:
      serviceUrl: "https://1dc87430-6519-41b2-82a3-926a875c5133.eu-de.secrets-manager.appdomain.cloud"
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: ibm-secret
            key: apiKey
